# Generated by Django 3.1.6 on 2021-02-09 21:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bakery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=14)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('recipient', models.CharField(max_length=28, null=True)),
            ],
            options={
                'verbose_name': 'Bakery',
                'verbose_name_plural': 'Bakeries',
                'db_table': 'bakeries',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction', models.IntegerField()),
                ('bakery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_bakery_fk', to='bakeries.bakery')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_customer_fk', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'db_table': 'sales',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('unit_price', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('tangible', models.BooleanField(default=True)),
                ('bakery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_bakery_fk', to='bakeries.bakery')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
    ]
