# Generated by Django 3.1.6 on 2021-02-09 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakeries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tangible',
        ),
    ]
